stages:
  - build

default:
  tags: [ "arch:amd64" ]  # Use runners with the "arch:amd64" tag

variables:
  BUILDER_IMAGE_VERSION_PREFIX: "v25.07-" # use either an empty string (e.g. "") for latest images or a version followed by a hyphen (e.g. "v25.05-")

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger" || $CI_PIPELINE_SOURCE == "pipeline" || $CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

build:
  stage: build
  image: ghcr.io/datadog/dd-trace-java-docker-build:${BUILDER_IMAGE_VERSION_PREFIX}base
  script:
    - export JAVA_HOME=$JAVA_17_HOME
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
      - ./**/build/test-results/**/**/TEST-*.xml
      - ./**/build/reports/*
    when: always
    reports:
      junit:
        - ./**/build/test-results/**/**/TEST-*.xml

