name: Feature Request
description: Create a public Feature Request. Note that these may not be addressed as it depeonds on capacity
labels: "type: feature request"
body:
  - type: textarea
    attributes:
      label: Describe the feature you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: |
        Please add a clear and concise description of your problem.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here
    validations:
      required: false
