package datadog.instrument.glue;

import static java.nio.charset.StandardCharsets.ISO_8859_1;
import static org.assertj.core.api.Assertions.assertThat;

import java.io.PrintWriter;
import java.io.StringWriter;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.util.CheckClassAdapter;

class DefineClassGlueGeneratorTest {

  @ParameterizedTest
  @ValueSource(strings = {"sun/misc", "jdk/internal/misc"})
  void generatedBytecodePassesVerification(String unsafeNamespace) {
    byte[] bytecode = DefineClassGlueGenerator.generateBytecode(unsafeNamespace);
    StringWriter errors = new StringWriter();

    // perform strict class verification, like -Xverify:all
    CheckClassAdapter.verify(new ClassReader(bytecode), false, new PrintWriter(errors));

    assertThat(errors.toString()).isEmpty();
  }

  /** ClassInjector inlines the glue unpacking, so check the packed glue decodes as expected. */
  @ParameterizedTest
  @ValueSource(strings = {"sun/misc", "jdk/internal/misc"})
  void packedGlueUnpacksToGeneratedBytecode(String unsafeNamespace) {
    byte[] originalBytecode = DefineClassGlueGenerator.generateBytecode(unsafeNamespace);
    String packedBytecode =
        "sun/misc".equals(unsafeNamespace) ? DefineClassGlue.V8 : DefineClassGlue.V9;

    // mirrors exactly what ClassInjector's generated bytecode does at runtime
    byte[] decodedBytecode = packedBytecode.getBytes(ISO_8859_1);

    assertThat(decodedBytecode).isEqualTo(originalBytecode);
  }
}
